
package "lib" (
  version = "$(pkg_version)"
  description = ""
  requires = "bin_prot core core_extended fieldslib patience_diff pcre ppx_assert.runtime-lib ppx_bench.runtime-lib ppx_expect.collector ppx_hash.runtime-lib ppx_inline_test.runtime-lib sexplib typerep variantslib"
  archive(byte  ) = "patdiff_lib.cma"
  archive(native) = "patdiff_lib.cmxa"
  plugin(byte  ) = "patdiff_lib.cma"
  plugin(native) = "patdiff_lib.cmxs"
  exists_if = "patdiff_lib.cma"
)
